# Generated by Django 4.0.4 on 2022-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='name',
        ),
        migrations.AddField(
            model_name='badge',
            name='Ref',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='UID',
            field=models.CharField(max_length=12),
        ),
    ]
