# Generated by Django 4.0.4 on 2022-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_remove_badge_name_badge_ref_alter_badge_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='Ref',
            field=models.CharField(max_length=4),
        ),
    ]
