# Generated by Django 4.0.4 on 2022-05-11 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='date_int',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
