# Generated by Django 4.0.4 on 2022-05-11 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0002_ownership_date_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='date_time_init',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='date_time_now',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownership',
            name='date_now',
            field=models.DateField(),
        ),
    ]
