# Generated by Django 4.0.4 on 2022-05-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0003_ownership_date_time_init_ownership_date_time_now_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='date_time_now',
            new_name='date_event_in',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='date_time_init',
            new_name='date_init',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='date_int',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='date_now',
        ),
    ]
